<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KelompokUktSeeder extends Seeder
{
    public function run()
    {
        DB::table('kelompok_ukt')->insert([
            // Administrasi Bisnis (D3)
            [
                'id_program_studi' => 1,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 1,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 1,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 1,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 1,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3600000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Akuntansi (D3)
            [
                'id_program_studi' => 2,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 2,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 2,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 2,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 2,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Manajemen Informatika (D3)
            [
                'id_program_studi' => 3,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 3,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 3,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 3,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 3,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Elektronika (D3)
            [
                'id_program_studi' => 4,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 4,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 4,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 4,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 4,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Kimia (D3)
            [
                'id_program_studi' => 5,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 5,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 5,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 5,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 5,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Listrik (D3)
            [
                'id_program_studi' => 6,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 6,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 6,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 6,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 6,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Mesin (D3)
            [
                'id_program_studi' => 7,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 7,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 7,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 7,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 7,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Sipil (D3)
            [
                'id_program_studi' => 8,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 8,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 8,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 8,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 8,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Telekomunikasi (D3)
            [
                'id_program_studi' => 9,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 9,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 9,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 9,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 9,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Akuntansi Manajemen (D4)
            [
                'id_program_studi' => 10,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 10,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 10,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 10,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 10,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 4750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Jaringan Telekomunikasi Digital (D4)
            [
                'id_program_studi' => 11,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 11,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 11,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 11,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 11,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Manajemen Pemasaran (D4)
            [
                'id_program_studi' => 12,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 12,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 12,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 12,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 12,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Manajemen Rekayasa Konstruksi (D4)
            [
                'id_program_studi' => 13,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 13,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 13,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 13,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 13,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 4750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Sistem Kelistrikan (D4)
            [
                'id_program_studi' => 14,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 14,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 14,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 14,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 14,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Elektronika (D4)
            [
                'id_program_studi' => 15,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 15,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 15,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 15,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 15,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Informatika (D4)
            [
                'id_program_studi' => 16,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 16,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 16,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 16,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 16,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknologi Kimia Industri (D4)
            [
                'id_program_studi' => 17,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 17,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 17,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 17,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 17,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Mesin Produksi dan Perawatan (D4)
            [
                'id_program_studi' => 18,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 18,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 18,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 18,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 18,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknik Otomotif Elektronik (D4)
            [
                'id_program_studi' => 19,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 19,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 19,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 19,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 19,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Bahasa Inggris (D3)
            [
                'id_program_studi' => 20,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 20,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 20,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 20,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 20,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3600000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Keuangan (D4)
            [
                'id_program_studi' => 21,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 21,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 21,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 21,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 21,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 4750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Teknologi Konstruksi Jalan, Jembatan, dan Bangunan Air (D3)
            [
                'id_program_studi' => 22,
                'nama_kelompok_ukt' => 'I',
                'nominal_kelompok_ukt' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 22,
                'nama_kelompok_ukt' => 'II',
                'nominal_kelompok_ukt' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 22,
                'nama_kelompok_ukt' => 'III',
                'nominal_kelompok_ukt' => 2250000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 22,
                'nama_kelompok_ukt' => 'IV',
                'nominal_kelompok_ukt' => 2750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_program_studi' => 22,
                'nama_kelompok_ukt' => 'V',
                'nominal_kelompok_ukt' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ]);
    }
}