<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class MahasiswaSeeder extends Seeder
{
    public function run()
    {
        $path = database_path('sql/mahasiswa.sql');
        $sql = File::get($path);
        DB::unprepared($sql);
        // $mahasiswaData = [
        //     [
        //         'id_user' => 5,
        //         'nama_mahasiswa' => 'DERRICK NAABIH PRABASWARA SAPUTRA',
        //         'nim_mahasiswa' => '2142520220',
        //         'angkatan_mahasiswa' => 2021,
        //         'semester_mahasiswa' => '20212',
        //         'jenjang_mahasiswa' => 'D',
        //         'id_program_studi' => 10,
        //         'jalur_masuk' => 'PSB/PMDK/SNMPN/SNMPTN',
        //         'alamat_ortu' => 'BURING REGENCY 3 KAV A6',
        //         'no_hp_aktif' => '895334344890',
        //         'no_telp_ayah' => '81334563553',
        //         'status_ortu' => 'Lengkap',
        //         'pekerjaan_ayah' => 'Lainnya',
        //         'pekerjaan_ibu' => 'Tidak bekerja',
        //         'jml_tanggungan' => 4,
        //         'anak_di_tanggung' => 2,
        //         'penghasilan_ayah' => 1000000,
        //         'penghasilan_ibu' => 0,
        //         'penghasilan_gabungan' => 1000000,
        //         'besaran_pln' => 22500,
        //         'besaran_pdam' => 59000,
        //         'pajak_mobil' => 0,
        //         'pajak_motor' => 333900,
        //         'id_periode' => 1,
        //         'status_verifikasi' => 'Diverifikasi',
        //         'id_kelompok_ukt' => 46,
        //     ],
        //     [
        //         'id_user' => 6,
        //         'nama_mahasiswa' => 'DIAN RAHAYU',
        //         'nim_mahasiswa' => '1931110017',
        //         'angkatan_mahasiswa' => 2019,
        //         'semester_mahasiswa' => '20201',
        //         'jenjang_mahasiswa' => 'E',
        //         'id_program_studi' => 4,
        //         'jalur_masuk' => 'PSB/PMDK/SNMPN/SNMPTN',
        //         'alamat_ortu' => 'JL. SULTAN AGUNG III/2',
        //         'no_hp_aktif' => '85607808512',
        //         'no_telp_ayah' => '85607808512',
        //         'status_ortu' => 'Janda',
        //         'pekerjaan_ayah' => 'Sudah Meninggal',
        //         'pekerjaan_ibu' => 'Pedagang Kecil',
        //         'jml_tanggungan' => 2,
        //         'anak_di_tanggung' => 1,
        //         'penghasilan_ayah' => 0,
        //         'penghasilan_ibu' => 750000,
        //         'penghasilan_gabungan' => 750000,
        //         'besaran_pln' => 100000,
        //         'besaran_pdam' => 50000,
        //         'pajak_mobil' => 0,
        //         'pajak_motor' => 237500,
        //         'id_periode' => 1,
        //         'status_verifikasi' => 'Diverifikasi',
        //         'id_kelompok_ukt' => 16,
        //     ],
        //     [
        //         'id_user' => 7,
        //         'nama_mahasiswa' => 'GALUH RASMI RAMANI',
        //         'nim_mahasiswa' => '1941160083',
        //         'angkatan_mahasiswa' => 2019,
        //         'semester_mahasiswa' => '20201',
        //         'jenjang_mahasiswa' => 'E',
        //         'id_program_studi' => 2,
        //         'jalur_masuk' => 'PSB/PMDK/SNMPN/SNMPTN',
        //         'alamat_ortu' => 'JL. INPRES NO. 10',
        //         'no_hp_aktif' => '81232312300',
        //         'no_telp_ayah' => '817389771',
        //         'status_ortu' => 'Lengkap',
        //         'pekerjaan_ayah' => 'Wiraswasta',
        //         'pekerjaan_ibu' => 'Tidak bekerja',
        //         'jml_tanggungan' => 5,
        //         'anak_di_tanggung' => 3,
        //         'penghasilan_ayah' => 5000000,
        //         'penghasilan_ibu' => 0,
        //         'penghasilan_gabungan' => 5000000,
        //         'besaran_pln' => 200000,
        //         'besaran_pdam' => 73500,
        //         'pajak_mobil' => 0,
        //         'pajak_motor' => 174000,
        //         'id_periode' => 1,
        //         'status_verifikasi' => 'Diverifikasi',
        //         'id_kelompok_ukt' => 7,
        //     ],
        //     [
        //         'id_user' => 8,
        //         'nama_mahasiswa' => 'GILBERT PRATHAMA PAJUK',
        //         'nim_mahasiswa' => '1942520045',
        //         'angkatan_mahasiswa' => 2019,
        //         'semester_mahasiswa' => '20201',
        //         'jenjang_mahasiswa' => 'D',
        //         'id_program_studi' => 10,
        //         'jalur_masuk' => 'PSB/PMDK/SNMPN/SNMPTN',
        //         'alamat_ortu' => 'JL. KH AGUS SALIM IV-25',
        //         'no_hp_aktif' => '82347132019',
        //         'no_telp_ayah' => '82347132019',
        //         'status_ortu' => 'Janda',
        //         'pekerjaan_ayah' => 'Tidak bekerja',
        //         'pekerjaan_ibu' => 'Lainnya',
        //         'jml_tanggungan' => 10,
        //         'anak_di_tanggung' => 2,
        //         'penghasilan_ayah' => 3000000,
        //         'penghasilan_ibu' => 2100000,
        //         'penghasilan_gabungan' => 5100000,
        //         'besaran_pln' => 150000,
        //         'besaran_pdam' => 69800,
        //         'pajak_mobil' => 0,
        //         'pajak_motor' => 208600,
        //         'id_periode' => 1,
        //         'status_verifikasi' => 'Diverifikasi',
        //         'id_kelompok_ukt' => 47,
        //     ],
        //     [
        //         'id_user' => 9,
        //         'nama_mahasiswa' => 'GAYATRI ANINGTYAS',
        //         'nim_mahasiswa' => '1941320137',
        //         'angkatan_mahasiswa' => 2019,
        //         'semester_mahasiswa' => '20211',
        //         'jenjang_mahasiswa' => 'D',
        //         'id_program_studi' => 10,
        //         'jalur_masuk' => 'PSB/PMDK/SNMPN/SNMPTN',
        //         'alamat_ortu' => 'JL BENGAWAN SOLO GANG MASJID NO 22 PAKUNDEN BLITAR',
        //         'no_hp_aktif' => '8121657809',
        //         'no_telp_ayah' => '82297713431',
        //         'status_ortu' => 'Lengkap',
        //         'pekerjaan_ayah' => 'Wiraswasta',
        //         'pekerjaan_ibu' => 'Lainnya',
        //         'jml_tanggungan' => 3,
        //         'anak_di_tanggung' => 1,
        //         'penghasilan_ayah' => 3500000,
        //         'penghasilan_ibu' => 2499999,
        //         'penghasilan_gabungan' => 5999999,
        //         'besaran_pln' => 312000,
        //         'besaran_pdam' => 188000,
        //         'pajak_mobil' => 0,
        //         'pajak_motor' => 253000,
        //         'id_periode' => 1,
        //         'status_verifikasi' => 'Diverifikasi',
        //         'id_kelompok_ukt' => 48,
        //     ],
        //     [
        //         'id_user' => 10,
        //         'nama_mahasiswa' => 'DILA SHOFIYANA',
        //         'nim_mahasiswa' => '2042530047',
        //         'angkatan_mahasiswa' => 2020,
        //         'semester_mahasiswa' => '20211',
        //         'jenjang_mahasiswa' => 'D',
        //         'id_program_studi' => 21,
        //         'jalur_masuk' => 'PSB/PMDK/SNMPN/SNMPTN',
        //         'alamat_ortu' => 'JL BUKIR SARI 47',
        //         'no_hp_aktif' => '81615627817',
        //         'no_telp_ayah' => '81615627817',
        //         'status_ortu' => 'Janda',
        //         'pekerjaan_ayah' => 'Sudah Meninggal',
        //         'pekerjaan_ibu' => 'Pedagang Kecil',
        //         'jml_tanggungan' => 2,
        //         'anak_di_tanggung' => 1,
        //         'penghasilan_ayah' => 0,
        //         'penghasilan_ibu' => 3450000,
        //         'penghasilan_gabungan' => 3450000,
        //         'besaran_pln' => 321000,
        //         'besaran_pdam' => 175000,
        //         'pajak_mobil' => 0,
        //         'pajak_motor' => 203000,
        //         'id_periode' => 1,
        //         'status_verifikasi' => 'Diverifikasi',
        //         'id_kelompok_ukt' => 104,
        //     ],
        //     [
        //         'id_user' => 11,
        //         'nama_mahasiswa' => 'DINA WAHYU SAFITRI',
        //         'nim_mahasiswa' => '2142530062',
        //         'angkatan_mahasiswa' => 2021,
        //         'semester_mahasiswa' => '20222',
        //         'jenjang_mahasiswa' => 'D',
        //         'id_program_studi' => 21,
        //         'jalur_masuk' => 'PSB/PMDK/SNMPN/SNMPTN',
        //         'alamat_ortu' => 'JL. LOMBOK',
        //         'no_hp_aktif' => '81217561125',
        //         'no_telp_ayah' => '81334474089',
        //         'status_ortu' => 'Lengkap',
        //         'pekerjaan_ayah' => 'Karyawan Swasta',
        //         'pekerjaan_ibu' => 'Tidak bekerja',
        //         'jml_tanggungan' => 4,
        //         'anak_di_tanggung' => 2,
        //         'penghasilan_ayah' => 3170000,
        //         'penghasilan_ibu' => 0,
        //         'penghasilan_gabungan' => 3170000,
        //         'besaran_pln' => 233000,
        //         'besaran_pdam' => 250000,
        //         'pajak_mobil' => 1000000,
        //         'pajak_motor' => 468500,
        //         'id_periode' => 1,
        //         'status_verifikasi' => 'Diverifikasi',
        //         'id_kelompok_ukt' => 104,
        //     ],
        //     [
        //         'id_user' => 12,
        //         'nama_mahasiswa' => 'ELSIANA DEWI',
        //         'nim_mahasiswa' => '2042520115',
        //         'angkatan_mahasiswa' => 2020,
        //         'semester_mahasiswa' => '20202',
        //         'jenjang_mahasiswa' => 'D',
        //         'id_program_studi' => 10,
        //         'jalur_masuk' => 'PSB/PMDK/SNMPN/SNMPTN',
        //         'alamat_ortu' => 'DSN. TUGUREJO',
        //         'no_hp_aktif' => '85732445172',
        //         'no_telp_ayah' => '85231904510',
        //         'status_ortu' => 'Lengkap',
        //         'pekerjaan_ayah' => 'Petani',
        //         'pekerjaan_ibu' => 'Tidak bekerja',
        //         'jml_tanggungan' => 4,
        //         'anak_di_tanggung' => 1,
        //         'penghasilan_ayah' => 700000,
        //         'penghasilan_ibu' => 0,
        //         'penghasilan_gabungan' => 700000,
        //         'besaran_pln' => 58026,
        //         'besaran_pdam' => 75000,
        //         'pajak_mobil' => 0,
        //         'pajak_motor' => 29500,
        //         'id_periode' => 1,
        //         'status_verifikasi' => 'Diverifikasi',
        //         'id_kelompok_ukt' => 50,
        //     ],
        //     [
        //         'id_user' => 13,
        //         'nama_mahasiswa' => 'ESTIAN',
        //         'nim_mahasiswa' => '1942530005',
        //         'angkatan_mahasiswa' => 2019,
        //         'semester_mahasiswa' => '20201',
        //         'jenjang_mahasiswa' => 'D',
        //         'id_program_studi' => 21,
        //         'jalur_masuk' => 'PSB/PMDK/SNMPN/SNMPTN',
        //         'alamat_ortu' => 'DS. SUGIHWARAS',
        //         'no_hp_aktif' => '82229275181',
        //         'no_telp_ayah' => '82230241334',
        //         'status_ortu' => 'Lengkap',
        //         'pekerjaan_ayah' => 'Karyawan Swasta',
        //         'pekerjaan_ibu' => 'Wirausaha',
        //         'jml_tanggungan' => 5,
        //         'anak_di_tanggung' => 3,
        //         'penghasilan_ayah' => 3000000,
        //         'penghasilan_ibu' => 2000000,
        //         'penghasilan_gabungan' => 5000000,
        //         'besaran_pln' => 50000,
        //         'besaran_pdam' => 110000,
        //         'pajak_mobil' => 0,
        //         'pajak_motor' => 201500,
        //         'id_periode' => 1,
        //         'status_verifikasi' => 'Diverifikasi',
        //         'id_kelompok_ukt' => 105,
        //     ],
        // ];

        // DB::table('mahasiswa')->insert($mahasiswaData);
    }
}