<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProgramStudiSeeder extends Seeder
{
    public function run()
    {
        DB::table('program_studi')->insert([
            [
                'id_jurusan' => 1,
                'nama_program_studi' => 'Administrasi Bisnis',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 2,
                'nama_program_studi' => 'Akuntansi',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 7,
                'nama_program_studi' => 'Manajemen Informatika',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 3,
                'nama_program_studi' => 'Teknik Elektronika',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 4,
                'nama_program_studi' => 'Teknik Kimia',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 3,
                'nama_program_studi' => 'Teknik Listrik',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 5,
                'nama_program_studi' => 'Teknik Mesin',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 6,
                'nama_program_studi' => 'Teknik Sipil',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 3,
                'nama_program_studi' => 'Teknik Telekomunikasi',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 2,
                'nama_program_studi' => 'Akuntansi Manajemen',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 3,
                'nama_program_studi' => 'Jaringan Telekomunikasi Digital',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 1,
                'nama_program_studi' => 'Manajemen Pemasaran',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 6,
                'nama_program_studi' => 'Manajemen Rekayasa Konstruksi',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 3,
                'nama_program_studi' => 'Sistem Kelistrikan',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 3,
                'nama_program_studi' => 'Teknik Elektronika',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 7,
                'nama_program_studi' => 'Teknik Informatika',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 4,
                'nama_program_studi' => 'Teknologi Kimia Industri',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 5,
                'nama_program_studi' => 'Teknik Mesin Produksi dan Perawatan',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 5,
                'nama_program_studi' => 'Teknik Otomotif Elektronik',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 1,
                'nama_program_studi' => 'Bahasa Inggris',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 2,
                'nama_program_studi' => 'Keuangan',
                'jenjang_pendidikan' => 'D-IV',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id_jurusan' => 6,
                'nama_program_studi' => 'Teknologi Konstruksi Jalan, Jembatan, dan Bangunan Air',
                'jenjang_pendidikan' => 'D-III',
                'created_at' => now(),
                'updated_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ]);
    }
}
